### ISSUE TITLE
keyboardEventCombo can throw an error

### ISSUE THREAD

**Issue by tones31** [blakeembrey/keyboard-manager#23]
In `keyboardEventCombo`, the call to `const keys = new Set<string>([e.key.toLocaleLowerCase()]);` can throw an error if `e.key` is undefined.

**Comment by blakeembrey** [comment]
Makes sense, I didn’t anticipate it being undefined except when using an unsupported browser. What key combination can I use to replicate this?

**Comment by blakeembrey** [comment]
As far as I can tell on all [supported browsers](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) it should always be a string, so I'd love to understand how I can replicate this if you know 🙏

**Comment by tones31** [comment]
Chrome for example triggers keydown events when you use autocomplete and
fires an even with an undefined key.

**Comment by blakeembrey** [comment]
Makes sense. I'm not sure how to replicate, but fixing seems simple. One approach would be to default to `"Unidenitifed"` like on the MDN documentation, or a similar string. Alternatively we can just omit it from the key combination altogether, but that might be odd - it'd result in empty key combinations or possibly just "meta" if it emits with one of those pressed.

**Comment by blakeembrey** [comment]
Do you have any strong opinions based on your usage?

**Comment by tones31** [comment]
Simply checking that the key is not undefined is sufficient in my opinion.

**Comment by blakeembrey** [comment]
Fixed in https://github.com/blakeembrey/keyboard-manager/releases/tag/v3.0.3
